#!/bin/bash 

. user-provided-env.sh

echo ""
<<<<<<< HEAD
echo `pwd`
=======
>>>>>>> 0c7ab13ea9c5cf9731648892fc926f321e900300
echo HADOOP FOLDER: $HADOOP_PREFIX
echo HADOOP VERSION: $HADOOP_VERSION
JAR_PREFIX=$HADOOP_PREFIX/share/hadoop/
ENVIRONMENTS_PREFIX=`pwd`/environments
AOP_PREFIX=`pwd`
JOBS_PREFIX=`pwd`/jobs
HADOOP_CORE_FILE_PATH=$JAR_PREFIX/common/hadoop-common-2.6.0.jar
HADOOP_MAPRED_FILE_PATH=$JAR_PREFIX/mapreduce/hadoop-mapreduce-client-core-2.6.0.jar
<<<<<<< HEAD
HADOOP_HDFS_FILE_PATH=$JAR_PREFIX/hdfs/hadoop-hdfs-2.6.0.jar
HADOOP_CORE_FILE=$(basename $HADOOP_CORE_FILE_PATH)
HADOOP_MAPRED_FILE=$(basename $HADOOP_MAPRED_FILE_PATH)
HADOOP_HDFS_FILE=$(basename $HADOOP_HDFS_FILE_PATH)
=======
HADOOP_CORE_FILE=$(basename $HADOOP_CORE_FILE_PATH)
HADOOP_MAPRED_FILE=$(basename $HADOOP_MAPRED_FILE_PATH)
>>>>>>> 0c7ab13ea9c5cf9731648892fc926f321e900300
RELEASE=`md5sum $HADOOP_CORE_FILE_PATH | cut -d " " -f 1`
RELEASE_PATH=$ENVIRONMENTS_PREFIX/$RELEASE
INSTRUMENTATION_PATH=$RELEASE_PATH/instrumentation
PATCHED_HADOOP_CORE_FILE=$RELEASE_PATH/$HADOOP_CORE_FILE
PATCHED_HADOOP_MAPRED_FILE=$RELEASE_PATH/$HADOOP_MAPRED_FILE
<<<<<<< HEAD
PATCHED_HADOOP_HDFS_FILE=$RELEASE_PATH/$HADOOP_HDFS_FILE
=======
>>>>>>> 0c7ab13ea9c5cf9731648892fc926f321e900300
SOURCE_AJC=`pwd`/src/$HADOOP_VERSION
echo SOURCE_AJC:$SOURCE_AJC


echo RELEASE: $RELEASE

echo ""
