#!/bin/bash 

echo $HADOOP_PREFIX
ENVIRONMENTS_PREFIX=`pwd`/environments
HADOOP_CORE_FILE_PATH=`ls $HADOOP_PREFIX/*.jar | grep core`
HADOOP_CORE_FILE=$(basename $HADOOP_CORE_FILE_PATH)
RELEASE=`md5sum $HADOOP_CORE_FILE_PATH | cut -d " " -f 1`
RELEASE_PATH=$ENVIRONMENTS_PREFIX/$RELEASE
PATCHED_HADOOP_CORE_FILE=$RELEASE_PATH/$HADOOP_CORE_FILE

echo Release: $RELEASE
