# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "../", "/vagrant/workspace"

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "base-hadoop.pp"
     puppet.module_path = "modules"
  end

  config.vm.define "master", primary: true do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.1.10"
  end

  config.vm.define "slave-1" do |slave_1|
    slave_1.vm.hostname = "slave-1"
    slave_1.vm.network "private_network", ip: "192.168.1.11"
  end

  config.vm.define "slave-2" do |slave_2|
    slave_2.vm.hostname = "slave-2"
    slave_2.vm.network "private_network", ip: "192.168.1.12"
  end

end
